<!-- Footer Starts Here -->
<!-- Footer Tag Starts Here -->
<div id="footer"> 
<!-- Column 1 Starts Here  -->
<!-- Column 1 links are generated by created information pages  -->
  <?php if ($informations) { ?>
  <div class="column">
    <h3><?php echo $text_information; ?></h3>
    <ul>
      <?php foreach ($informations as $information) { ?>
      <li><a href="<?php echo $information['href']; ?>"><?php echo $information['title']; ?></a></li>
      <?php } ?>
    </ul>
  </div>
  <?php } ?>
<!-- Column 1 Ends Here --> 

<!-- Column 2 Starts Here  -->
<!-- Static Links - optional --> 
  <div class="column">
    <h3><?php echo $text_placeholder; ?></h3><!-- Column Title -->
    <ul>
      <li><a href="<?php echo $contact; ?>"><?php echo $text_contact; ?></a></li>
      <li><a href="#"><?php echo $text_placeholder; ?></a></li> <!-- placeholder link -->
      <li><a href="#"><?php echo $text_sitemap; ?></a></li><!-- placeholder link -->
    </ul>
  </div>
<!-- Column 2 Ends Here -->

<!-- Column 3 Starts Here -->
<!-- Static Links - optional -->
  <div class="column">
    <h3><?php echo $text_extra; ?></h3>
    <ul>
      <li><a href="<?php echo $manufacturer; ?>"><?php echo $text_manufacturer; ?></a></li>
      <li><a href="#"><?php echo $text_placeholder; ?></a></li><!-- placeholder link -->
      <li><a href="#"><?php echo $text_placeholder; ?></a></li><!-- placeholder link -->
      <li><a href="#"><?php echo $text_placeholder; ?></a></li><!-- placeholder link -->
    </ul>
  </div>
<!-- Column 3 Ends Here -->

<!-- Column 4 Starts Here -->
<!-- Static Links - optional -->
  <div class="column">
    <h3><?php echo $text_account; ?></h3>
    <ul>
      <li><a href="<?php echo $account; ?>"><?php echo $text_account; ?></a></li>
      <li><a href="#"><?php echo $text_placeholder; ?></a></li><!-- placeholder link -->
      <li><a href="#"><?php echo $text_placeholder; ?></a></li><!-- placeholder link -->
      <li><a href="<?php echo $newsletter; ?>"><?php echo $text_newsletter; ?></a></li>
    </ul>
  </div>
<!-- Column 4 Ends Here -->

</div>
<!-- Footer Tag Ends Here -->
<!-- Footer Ends Here -->

<!-- Copyright Code Starts Here -->
<div id="powered"><?php echo $powered; ?></div>
<!-- Copyright Code Ends Here -->

</div>
<!-- End of page container -->
</body>
</html>